import React from 'react';
import { Shield, FileText, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import './Legal.css';

const Legal = ({ mode }) => {
  const navigate = useNavigate();
  const isPrivacy = mode === 'privacy';

  return (
    <div className="legal-page">
      <div className="legal-container glass-card">
        <button className="back-btn" onClick={() => navigate(-1)}>
          <ArrowLeft size={18} /> Back
        </button>
        
        <header className="legal-header">
          {isPrivacy ? <Shield size={48} className="legal-icon" /> : <FileText size={48} className="legal-icon" />}
          <h1>{isPrivacy ? 'Privacy Policy' : 'Terms of Service'}</h1>
          <p>Last updated: May 2026</p>
        </header>

        <section className="legal-content">
          {isPrivacy ? (
            <>
              <h2>1. Information We Collect</h2>
              <p>We collect information you provide directly to us, such as when you create an account, generate a trip, or post to the live map. This includes your name, email, and travel preferences.</p>
              
              <h2>2. How We Use Your Data</h2>
              <p>Your data is used to personalize your travel itineraries, enable community interactions, and provide platform support. We use Groq AI to process your preferences into itineraries.</p>
              
              <h2>3. Data Sharing</h2>
              <p>We do not sell your personal data. We share information with third-party services (like Google OAuth, Pexels, and Open-Meteo) only to provide the requested platform features.</p>
            </>
          ) : (
            <>
              <h2>1. Acceptance of Terms</h2>
              <p>By accessing or using Travio, you agree to be bound by these Terms of Service. If you do not agree, you may not use the platform.</p>
              
              <h2>2. User Content</h2>
              <p>You retain ownership of the content you post to the Live Map and Community Hubs. However, you grant Travio a license to display and distribute this content within the platform.</p>
              
              <h2>3. AI-Generated Content</h2>
              <p>Itineraries are generated by AI and should be used for informational purposes only. We do not guarantee the accuracy of flight prices, hotel availability, or weather forecasts.</p>
            </>
          )}
        </section>
      </div>
    </div>
  );
};

export default Legal;
